= Developers Reference

include::attributes.adoc[]

== Overview

The goal of {qr-name} is to provide developers with tools that are easy to use
and understand. We believe that a procedural and imperative style of writing
programs, or thinking about tasks in programs, is broadly understood and
valuable model. With {qr-name} we try to support this, rather than introducing
any new concepts for _streams_, _futures_ or _promises_.

:DISTR: https://en.wikipedia.org/wiki/Distributed_computing

With {qr-name} developers should feel enabled to write code in a _normal_ way.
However, it is our mission to raise awareness of things that are hard to
consider, when building {DISTR}[distributed systems]. The tools try to convey
these considerations, by making them transparent and part of the API.

In the next couple of sections we'll look closer at the `QueryBuilder` and the
`ResponseBuilder` types. We'll discuss how to use them in detail, and try to
explain the concepts behind them, and the intention of their implementation.

== `QueryBuilder`

The `QueryBuilder` class is the central entry-point, and provides a fluent
builder-API, for publishing queries. It's provided as a bean, by enabling
{qr-name}, using the `@EnableQueryResponse` annotation. It may be injected
as a dependency to provide access from methods in any Spring component.

We recommend injecting it via the component constructor, and keeping it as a
private field. The `findAuthors()` method below, shows how to access the
`queryBuilder` field in order to publish a query.

Queries are built and published using the `queryFor(..)` _initial_ method.
Any of the _terminal_ calls to either `orEmpty()`, `orDefaults(..)` or
`orThrows(..)` will block on the calling thread.

[source,java]
----
include::{examples-src}/querying/src/main/java/examples/Authors.java[tags=authorsClass]
----

In the example above, the published query is defined by the string **term** 
`"authors"`. This is how the most basic contract of {qr-pfx} is defined. Any
string or text term may be published as a query.

The second argument is the expected type of any received response elements. It
is not published with the query, but rather used to coerce or interpret any
received responses. This means that regardless of the payload of any response,
in this case {qr-name} will attempt to read the response elements as the
declared type `String.class`.

Since the call to `orEmpty()` will block, users have to specify one or more
blocking _conditional_. In the example above, the call to `waitingFor(..)`
defines that the call will block for around 800 milliseconds.

Constructing queries with the `QueryBuilder` revolves around a composition of
_initial_, _conditional_, the odd _informal_ and exactly one _terminal_ method
call. In the table below is a short description of the different methods and
types.

[cols="1,1,3"]
.`QueryBuilder` fluid API method types
|===
| Method              | Type          | Description

| `queryFor(..)`      | _initial_     | Creates a new builder for a query
| `waitingFor(..)`    | _conditional_ | Specifies the waiting/blocking condition
| `takingAtMost(..)`  | _conditional_ | Sets a limit condition, a maximum
| `takingAtLeast(..)` | _conditional_ | Sets a limit condition, a minimum
| `onError(..)`       | _informal_    | Allows for explicit logging etc.
| `orEmpty()`         | _terminal_    | Terminates with empty, after conditionals are evaluated
| `orDefaults(..)`    | _terminal_    | Terminates with some defaults, after conditionals are evaluated
| `orThrow(..)`       | _terminal_    | Terminates by throwing, after conditionals are evaluated
|===

Let's take a closer look at each of the builder method types.

=== _Initial_ methods

At the moment there's only one _initial_ method and it's declared as:

```java
  public <T> ChainingQueryBuilder<T> queryFor(String term, Class<T> type)
```

So we can query for any `String` **term** and given the expected mapped or
coerced **type** as a `Class<T>`. The returned `ChainingQueryBuilder<T>`
provides the capabilities of the fluid API.

=== _Conditional_ methods

All _conditional_ properties can be composed together by the `QueryResponse`
builder API, to define whether a query is successful or not. If an executing
query is completed in a *successful* way, fulfilling the _conditionals_, it will
return and not consume any more responses.

* `waitingFor(..)` - a _conditional_ that defines the amount of blocking time
  that is acceptable. In many cases a query must have a defined blocking time
  in order to be easily evaluated as successful or not. Is considered
  *successful* if _any_ responses are received within the given time limit. The
  API for is declared to provide a few different ways to specify the timeout.

** `waitingFor(long millis)`
** `waitingFor(long amount, TemporalUnit timeUnit)`
** `waitingFor(Duration duration)`

* `takingAtMost(int atMost)` - defines a limiting _conditional_ on the aggregated
  number of received elements. The blocking client evaluates to *successful*,
  and returns, if the given amount if reached.

* `takingAtLeast(int atLeast)` - defines a minimum _conditional_ on the number
  of received element. The query evaluates to *successful*, only if at least
  the given number of elements has been consumed.

=== _Terminal_ methods

=== _Informal_ methods



Preserve resources specific to the current needs and protect your services,
by limiting the amount of data consumed.

```java
  var authors = queryBuilder.queryFor("authors", String.class)
                  .takingAtMost(10)
                  .waitingFor(800)
                  .orDefaults(Authors.defaults());
```

Express constraints and react accordingly, throwing on an unfulfilled query, as
an option to lenient handling with defaults.

```java
  var offers = queryBuilder.queryFor("offers/rental", Offer.class)
                  .takingAtLeast(10)
                  .takingAtMost(20)
                  .waitingFor(2, ChronoUnit.SECONDS)
                  .orThrow(TooFewOffersConstraintException::new);
```

Optional capabilities to handle exceptions and errors are built-in and very
easy to use.

```java
  var offers = queryBuilder.queryFor("offers/rental", NewOffer.class)
                  .takingAtLeast(3)
                  .waitingFor(400)
                  .onError(error -> LOG.error("Failure!", error))
                  .orThrow(TooFewOffersConstraintException::new);
```

== `ResponseBuilder`

TODO!

Batch responses provide developers with more options to tune and throttle a
system using Query/Response across many services.

```java
  responseBuilder.respondTo("offers/monday", Offer.class)
      .withBatchesOf(20)
      .from(offers.findAllOffersByDayOfWeek(Calendar.MONDAY));
```

Dynamic responses are easy to build, with an API that suits modern Java, using
lazy calls to suppliers of data.

```java
  responseBuilder.respondTo("users/current", Token.class)
      .withBatchesOf(128)
      .suppliedBy(userTokenService::findAllCurrentUserTokens);
```
