= Getting Started

include::attributes.adoc[]

{qr-name} makes it really easy to extend {spring-boot-name} stand-alone,
production-grade applications, that are using {spring-amqp-name}. We have taken
a working pattern for building highly decoupled evolving service architectures,
and wrapped it in a developer friendly library.

== System Requirements

{qr-name-and-version} requires at least {spring-boot-name-and-version} and
{java-name-and-version}, and should work for later releases too.

:Maven: https://maven.apache.org
:Gradle: https://gradle.org

It is distributed as a {Maven}[Maven] dependency, and is known to work well with
Maven 3.3+. Using the dependency with {Gradle}[Gradle] should work too.

:Quickstart: https://github.com/olle/query-response-spring-amqp#quickstart

The current {Quickstart}[Quickstart] information, available on the projects
{qr-gh-link}[Github page], provides a short snippet on the currently best way
to add the Maven dependency.

== Installation

Enabling {qr-name} is done by loading the `QueryResponseConfiguration` class.
The most simple way to do this, is annotating your {spring-boot-name}
application starter with the `@EnableQueryResponse` annotation.

[source,java]
----
include::{examples-src}/myapp/src/main/java/app/MyApp.java[lines=9..17]
----

NOTE: This annotation will do nothing more but to import the
      `QueryResponseConfiguration` class.

== Queries

TODO!

== Responses

TODO!

== Monitoring UI

TODO!
