= Query/Response for Spring® AMQP
Olle Törnström

include::attributes.adoc[]

== Foreword

:1010: https://twitter.com/fgeorge52
:1020: https://youtu.be/yPf5MfOZPY0
:1030: https://en.wikipedia.org/wiki/Service-level_objective

_Sometime around 2015 I came across a presentation with {1010}[Fred George],
 about the {1020}[Challenges in Implementing Microservices]. It's a great
 talk, with lots of lessons-learned that are really relevant; still are
 today, if you ask me. Experience comes from learning through failures, and at
 this point in time I was well aware of the problems that come with services
 using REST-ful APIs to call other services. I had already seen how latencies
 could spike and availability get lost, as calls from service A to B were
 actually depending on service B calling service C. It was a mess._

_In his talk George lands at the question "Synchronous or Asynchronous?" and
 proceeds to describe, what he calls, the "Needs Pattern". Service A would,
 instead of calling service B, publish a request, and service B would be able
 to pick it up and send back a response. After hearing this I began to think
 a lot about the effects of moving to an asynchronous way of communication
 between services. There was clearly a lot more here than just decoupling
 service endpoints and call latencies. Something more profound._

_The **Query/Response pattern**, that I arrived at, challenges developers to
 really think hard about responsibility and autonomy in architecture and
 design. It gives very few guarantees (almost none actually), which will force
 decisions about {1030}[Service Level Objectives (SLA)], as well as
 resilience and availability, at a much earlier stage in the design and
 development process. It literally turns things around, which we will see._

== About This Document

TODO!

include::getting-started.adoc[leveloffset=+1]
include::developers-reference.adoc[leveloffset=+1]
include::the-query-response-protocol.adoc[leveloffset=+1]
