= Query/Response Events

== Metrics or "Stats"

Participating nodes in a Query/Response topology will broadcast events of
structured statistics for the UI and monitoring applications to consume. The
common data-shape encapsulates a way to communicate measurements, events and
node-identifying and describing meta-data.

The entry structure and format is encoded as a JSON UTF-8 encoded string.

```json
{
  "elements": [
    {
      "key": <string>,
      "value": <string|number>,
      "timestamp": <OPTIONAL:number>,
      "uuid": <OPTIONAL:string>
    },
    ...
  ]
}
```

The `key` and `value` property pairs are used to encode any measurement. The
`timestamp` is an optional property, that can be used to associate a measurement
with a point in time since the EPOCH, in milliseconds.

The `uuid` property is used to identify the publishing node, during it's
lifetime - effectively creating an aggregate for statistics to present. This
means that in practice there are operational metrics which may _come and go_
as well as logical statistics which may pertain to the topology or cluster of
nodes.

=== Table of published statistics

[cols="2,2,1,1,3"]
|===
| Key    | Value    | Timestamp    | UUID    | Description

| `count_queries`      | Number    | **-**    | **YES**    | Number of published queries
| `count_consumed_responses` | Number | **-** | **YES** | Number of consumed responses
| `count_published_responses` | Number | **-** | **YES** | Number of published respones
| `count_fallbacks` | Number | **-** | **YES** | Number of _fallbacks_ (no responses)
| `max_latency` | Number | **-** | **YES** | Largest recorded time between query and response, in milliseconds
| `min_latency` | Number | **-** | **YES** | Smallest recorded time between query and response, in milliseconds
| `avg_latency` | Number | **-** | **YES** | Average time between query and response, in milliseconds
|===
